import 'package:sqflite/sqflite.dart';

class DirectorSeeder {
  static Future<void> seed(Database db) async {
    List<Map<String, dynamic>> directors = [
      {
        'identification': '001-1234567-8',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Juan',
        'last_name': 'Pérez',
        'birth_date': '1980-01-01',
        'address': 'Avenida 1, Ciudad 1',
        'phone_number': '809-345-6789',
      },
      {
        'identification': '002-2345678-9',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Carlos',
        'last_name': 'Rodríguez',
        'birth_date': '1975-03-22',
        'address': 'Avenida 3, Ciudad 3',
        'phone_number': '809-456-7890',
      },
      {
        'identification': '003-3456789-0',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Miguel',
        'last_name': 'García',
        'birth_date': '1983-05-15',
        'address': 'Avenida 5, Ciudad 5',
        'phone_number': '809-567-8901',
      },
      {
        'identification': '004-4567890-1',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'José',
        'last_name': 'Martínez',
        'birth_date': '1978-09-30',
        'address': 'Avenida 7, Ciudad 7',
        'phone_number': '809-678-9012',
      },
      {
        'identification': '005-5678901-2',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Luis',
        'last_name': 'Sánchez',
        'birth_date': '1982-11-11',
        'address': 'Avenida 9, Ciudad 9',
        'phone_number': '809-789-0123',
      },
      {
        'identification': '006-6789012-3',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Fernando',
        'last_name': 'Ramírez',
        'birth_date': '1979-04-20',
        'address': 'Avenida 11, Ciudad 11',
        'phone_number': '809-890-1234',
      },
      {
        'identification': '007-7890123-4',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Roberto',
        'last_name': 'López',
        'birth_date': '1981-07-25',
        'address': 'Avenida 13, Ciudad 13',
        'phone_number': '809-901-2345',
      },
      {
        'identification': '008-8901234-5',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Jorge',
        'last_name': 'Torres',
        'birth_date': '1984-06-10',
        'address': 'Avenida 15, Ciudad 15',
        'phone_number': '809-012-3456',
      },
      {
        'identification': '009-9012345-6',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Antonio',
        'last_name': 'Vásquez',
        'birth_date': '1977-12-18',
        'address': 'Avenida 17, Ciudad 17',
        'phone_number': '809-123-4567',
      },
      {
        'identification': '010-0123456-7',
        'photo': 'https://c0.klipartz.com/pngpicture/876/963/gratis-png-silueta-del-hombre-silueta-persona-cabeza-humana-sombra.png',
        'first_name': 'Daniel',
        'last_name': 'González',
        'birth_date': '1986-03-05',
        'address': 'Avenida 19, Ciudad 19',
        'phone_number': '809-234-5678',
      },
      {
        'identification': '011-1234567-8',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Ana',
        'last_name': 'Gómez',
        'birth_date': '1985-02-14',
        'address': 'Avenida 2, Ciudad 2',
        'phone_number': '809-567-8901',
      },
      {
        'identification': '012-2345678-9',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'María',
        'last_name': 'Fernández',
        'birth_date': '1990-07-09',
        'address': 'Avenida 4, Ciudad 4',
        'phone_number': '809-678-9012',
      },
      {
        'identification': '013-3456789-0',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Carmen',
        'last_name': 'Pérez',
        'birth_date': '1983-08-30',
        'address': 'Avenida 6, Ciudad 6',
        'phone_number': '809-789-0123',
      },
      {
        'identification': '014-4567890-1',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Lucía',
        'last_name': 'Mendoza',
        'birth_date': '1979-11-14',
        'address': 'Avenida 8, Ciudad 8',
        'phone_number': '809-890-1234',
      },
      {
        'identification': '015-5678901-2',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Elena',
        'last_name': 'Morales',
        'birth_date': '1982-05-22',
        'address': 'Avenida 10, Ciudad 10',
        'phone_number': '809-901-2345',
      },
      {
        'identification': '016-6789012-3',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Patricia',
        'last_name': 'Santos',
        'birth_date': '1987-12-03',
        'address': 'Avenida 12, Ciudad 12',
        'phone_number': '809-012-3456',
      },
      {
        'identification': '017-7890123-4',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Sofía',
        'last_name': 'Rodríguez',
        'birth_date': '1992-04-19',
        'address': 'Avenida 14, Ciudad 14',
        'phone_number': '809-123-4567',
      },
      {
        'identification': '018-8901234-5',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Gabriela',
        'last_name': 'Reyes',
        'birth_date': '1989-06-27',
        'address': 'Avenida 16, Ciudad 16',
        'phone_number': '809-234-5678',
      },
      {
        'identification': '019-9012345-6',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Andrea',
        'last_name': 'Pineda',
        'birth_date': '1986-09-11',
        'address': 'Avenida 18, Ciudad 18',
        'phone_number': '809-345-6789',
      },
      {
        'identification': '020-0123456-7',
        'photo': 'https://w7.pngwing.com/pngs/394/73/png-transparent-computer-icons-woman-female-silhouette-woman-people-head-black.png',
        'first_name': 'Natalia',
        'last_name': 'González',
        'birth_date': '1981-10-14',
        'address': 'Avenida 20, Ciudad 20',
        'phone_number': '809-456-7890',
      },
    ];

    for (var director in directors) {
      await db.insert('directors', director);
    }
  }
}
